### PR TITLE
Search memo

### PR DESCRIPTION
**Pull request by h-michael**
Can search memo with query

 - [x] search with query
 - [x] update doc

next feature
 -  with Ctrlp

### CODE REVIEW

**Comment by wadackel** [comment]
Thx!
Can I merge at the stage when todo is completed😃?

**Comment by h-michael** [comment]
@tsuyoshiwada 
Can I  separate CtrlP interface PR ?
And sorry, this is my first Vimscript.

**Comment by wadackel** [comment]
of course 💪 !

> And sorry, this is my first Vimscript.

No probrem, me to :)

**Comment by wadackel** [comment]
I am going now, so I will will check later 😃

**Comment by wadackel** [comment]
Sorry for late response... :pray:
Very thanks! merged.

**Pull request merged**
